### ISSUE TITLE
Occult Entrance and Water won't load

### ISSUE THREAD

**Issue by GigaLem** [SimonN/LixD#213]
This might be because I'm using an older version but
![bug](https://user-images.githubusercontent.com/31464930/29855896-7d663fb4-8d0c-11e7-8fc3-f679898a25c3.png)

**Comment by SimonN** [comment]
Hi,

thanks for the report! This happens when your graphics card cannot handle images wider than 4096 pixels. I thought that this happened only on my 11-year-old-laptop, therefore I've never bothered. Good to know that others have this limitation, too!

**Workaround:** Shorten the images: Open these two images in MS-Paint and resize them to 4000 or even 2000 pixels wide. The animation will look cut-off, but the tiles will load with correct physics.

-- Simon
