### ISSUE TITLE
Add a proper icon/logo

### ISSUE THREAD

**Issue by Lucki** [SimonN/LixD#223]
Add a nice Icon/Logo which represents the game. This can then be used as a desktop icon.
To do so it has to be cubic to look nice and at least `48x48` pixels, more is better, scalable in `.svg` would be perfect. To get an idea you can have a look into `/usr/share/icons/hicolor/*/apps/` or `/usr/share/pixmaps`. Transparency is also supported.

**Comment by SimonN** [comment]
Very sensible. 0.8.5 will have XDG base dir conformace, but no icon yet. Drawing is hard, I'll try myself and ask around.

**Comment by SimonN** [comment]
Lucki uploaded: https://abload.de/img/lixzcs32.png

SimonN: wow, this is awesome, and perfectly matching in style!
SimonN: the feet are paws, not shoes. Shoeld get a small vertical slash near the bottom instead of the large horizontal slash, and be colored like the skin
SimonN: there is a section of skin-color over the lower arm, under the face. I'm still deciding whether that should be skin or hair
SimonN: and the hair color is slightly more golden
SimonN: overall I'm very pleased and will be happy to merge this
