### ISSUE TITLE
Feature request: Scroll level with arrow keys.

### ISSUE THREAD

**Issue by stavrossk** [SimonN/LixD#287]
Hi, is it possible to add the functionality or an option to scroll the level with the keyboard's arrow keys?

Thanks,
Stavros

**Comment by SimonN** [comment]
Hi, yeah, I can consider 4 remappable hotkeys for scrolling.

Arrow left/right, by default, is bound to select only left/right-facing lix. I'm inclined to leave these default bindings, but keep everything remappable.

In the meantime, try right-click scrolling: Hold the right mouse button and move the mouse around. This is the fastest and most precise way to scroll. If you'd still like keyboard scrolling even after trying right-click scrolling, I can look into it.

**Comment by stavrossk** [comment]
@SimonN Thank you, I didn't know about right mouse buttion scrolling (sorry I played the game yesterday for the first time). Now that I know about it, arrow keys scrolling would be a welcome addition but not necessary for me.

Thanks,
Stavros

**Comment by SimonN** [comment]
Cool!

Yeah, I'm aware that the right-button scrolling is hard to discover. It's a great feature when one is accustomed to it, but it's so hard to explain to newcomers. I'd have to disable the mouse-at-screen-edge and display annoying helper text -- but then again, some people like edge scrolling better. And when the program knows what the user wants, it should do it, not teach the user of a different way. :-)

Arrow keys might still interesting if somebody plays with a touchpad instead of a mouse. For now, I'll keep it on the wishlist with lower priority. If anybody wants arrow-key scrolling more urgently: Feel free to post here.

**Comment by SimonN** [comment]
I think I won't implement arrow-key scrolling.

How does hold-to-scroll a.k.a. right-click scrolling feel after a couple days? I believe it outperforms any other scrolling method. It could be more discoverable, I'll have to get more feedback.

**Comment by stavrossk** [comment]
@SimonN  Yes, there is not need to implement it since right-cilck scrolling works better and after a few days of playing I like it better.

**Comment by SimonN** [comment]
Awesome! Thanks for the feedback!
