### ISSUE TITLE
building on debian problems

### ISSUE THREAD

**Issue by alexmyczko** [SimonN/LixD#307]
hi Simon

i'm having issues to build this on debian:

http://sid.ethz.ch/debian/lix/ check the *.build file

any hints welcome...

**Comment by SimonN** [comment]
Thanks! I've noticed:
```
Search for versions of enumap (1 package suppliers)
debian/rules:19: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Segmentation fault
```
That looks like the D build toolchain segfaulted before Lix was successfully compiled. That's strange. Expected output during compilation by dub be something like
```
lix <someVersion>: building configuration "application"...
Compiling Lix 0.9.11...
```
**Idea:** You can produce even better debugging output by `dub --verbose build` instead of `dub -v build`. Maybe it'll be clearer what crashes from that output.

**Idea:** dub fetches bindings and puts them somewhere, maybe it segfaults during that stage already? The [Arch Linux package recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lix) calls dub with `--cache=local` to force placement of fetched dependencies in a local dir, not in user's home. Maybe try that? I.e., `dub --vverbose build --cache=local`, or copy the entire command-line from the Arch recipe.

---

(By coincidence, this week, I've troubleshot the build on Ubuntu where we had linker errors. The answer on Ubuntu was to change in `dub.json` the required library `"allegro"` to `"allegro-5"`. I'll release 0.9.12 this weekend and it'll have this change. But you don't even seem to get to linking; some tool looks like it segfaults before/during compilation.)

**Comment by SimonN** [comment]
tarzeau (alexmyczko) met me on IRC (quakenet #lix) and we conjectured that Debian packages may not access the internet during building. My advice thus was:

You can try to build Lix outside of the Debian build system once, this will populate `~/.dub/packages`. Then take the D sources in there, put them where it makes the Debian build system is happy, and build by pointing dub at that directory and prohibiting internet lookup.
Then build inside the D system with `dub --skip-registry=all`, but you must also force `dub` to look at the prepared bindings (see Arch recipe for how to do that). There is `dub --cache=local` to "put any fetched packages in the specified location", but I don't know if dub will look into there when it doesn't fetch anything. Again, the Arch build script to make a package only from local dependencies can be helpful (even though it fetches the deps from the net): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lix

**Comment by SimonN** [comment]
D builds on Debian seem problematic these months.

 [Thread on D forums about a failing Hello World on Debian 64-bit](https://forum.dlang.org/thread/jjaynewwdsyntyehvahq@forum.dlang.org)
[Bug report against D, Hello World segfaults](https://issues.dlang.org/show_bug.cgi?id=18350) [1]

GDC ships as a Debian package (unlike DMD: for DMD, you must [manually add a package repository](http://d-apt.sourceforge.net/)). Debian's [policy demands that GDC be a dependency of any D-using Debian package](https://packages.debian.org/sid/gdc). But with GDC, the Lix source doesn't compile -- I seem to rely on cutting-edge language features. [2]

Furthermore, on a virtual machine with 32-bit Debian 9.4, dub took a long time to check versions of Lix's dub dependencies -- about 30 minutes for all dependencies. Then, fetching the selected versions timed out while storing the fetched zip file. (Might be related to a slow virtual machine, accessing webpages took ~2 minutes even though downloads were faster afterwards.)

Both for DMD and for GDC, the following workaround didn't help: Fetch all dub dependencies manually, e.g., run dub on a machine where everything works and copy its dub package cache over to the Debian virtual machine. This fails for DMD because of the segfaults (like [1] above) and it fails for GDC because Lix relies on newer D than what GDC offers ([2] above).

**Comment by SimonN** [comment]
To work around dub's fetching problems on Debian, you can download [my dub package cache directory](http://www.lixgame.com/etc/dubdir-2018-05-24.zip) and extract into `~./dub/`. I.e., generate a tree structure with
```
~/.dub/packages/allegro-4.0.1_5.2.0/allegro/README.md
```
Furthermore, to skip dub's online checks altogether, add [my dub.selections.json](http://www.lixgame.com/etc/dub.selections.json) to your Lix directory (where Lix's README.md sits) and build with `dub --skip-registry=all`.

**Comment by alexmyczko** [comment]
Thanks for all the help, meanwhile, the ITP is active again and the packaging is done:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=617664
http://phd-sid.ethz.ch/debian/lix/
