### ISSUE TITLE
Translate key names

### ISSUE THREAD

**Issue by Wuzzy2** [SimonN/LixD#337]
Key names should be translated as well, e.g. “Delete”, “Enter”, “Space”, “Control”, “Shift”…

**Comment by SimonN** [comment]
Interesting idea.

Translating key names isn't as straightforward as translating other string. The key names come from Allegro 5 (a library) and aren't internationalized. I'd have to write extra code here.

I prefer the English key names even when I'm talking to other Germans. But I don't know how prevalent this is. Is "Umschalt" really more understandable in German than "Shift"? Do you prefer German key names because they're clearer to you, or because you're astonished by German UI with English key names?

**Comment by Wuzzy2** [comment]
The keyboard keys do have established (!) German names, they *are* prevalent and are printed in German names or abbreviations on the actual keyboard.
So there's no excuse to keep them English on purpose. This just defeats the point of having a German translation in the first place.

**Comment by SimonN** [comment]
I apologize for leaving you hanging here, and for having been unclear 5 years ago.

> So there's no excuse to keep them English on purpose.

The excuse was _not_ about my personal preference. I've set Lix to English.

The excuse was: It's hard to implement because neither Lix nor Allegro have easy support for key translations. I'll have to write better custom language support in Lix to get it done. And in 2018, other things had higher priority than that.

Recently, for i18n, I've looked into #335 (translating skills). When that is done and released, I can look into translating the keys.

---

Can I use this image as a reference for the established key names, or do you suggest other names?
https://info-ag.coderdojo-saar.de/wp-content/uploads/2021/01/Screenshot-2021-01-01-at-13.36.01.png

Tab, backspace, enter: Lix shows these as arrows, e.g., ⌫ for backspace. They need no translation.

What do we do with shift and caps lock? Lix's keymapping buttons abbreviates the names to 2-5 characters when you bind mutiple keys to the same function. Should we translate "LShift", "RShift", "Caps Lock" to "LUmschalt", "RUmschalt", "Feststelltaste" and accept "LUm"/"LU" as abbreviations?

Maybe I should look for some unicode symbols, nice fat arrows, and have "L(fat up arrow)" for LShift. I think that's better if room is tight.

**Comment by Wuzzy2** [comment]
The keyboard image is correct. "LUmschalt" and "RUmschalt" is also OK. But "LUm" and "LU" are bad abbreviations, nobody uses or know that.

**Comment by Wuzzy2** [comment]
Yes, Unicode is great (assuming the font supports these glyphs :D ).

**Comment by SimonN** [comment]
Fixed in 0.10.17, which released today. I resorted to "⇧" instead of "L⇧".

Feel free to re-open or file new bugs if keys are wrong. I don't have German keyboards here to test, and I don't have a German-language computer setup. I'll see when I can find a German Windows machine for testing.
