### ISSUE TITLE
Imploder animation is too short and subtle

### ISSUE THREAD

**Issue by Wuzzy2** [SimonN/LixD#339]
I think the imploder animation is too fast and subtle in 0.9.17.
It's so short it's almost invisible, there are also no longer any particle effects. It almost looks like as if the lix just disappears.

I liked old imploder animation from 2016 much better.

The request in this issue is to improve the imploder animation to look more visually appealing. It should have the same quality as in 2016 or better.

**Comment by SimonN** [comment]
Yes, both imploders and exploders should get pixels. Ideally, imploder pixels fly into the black hole instead of down the screen. :-) The imploder anim also plays much faster than designed by geoo; this implementation in D Lix is a leftover hack.

This issue comes with a better description than #205 (introduce particle effects for ploders) and I'll close #205 in favor of this.
