### ISSUE TITLE
Error in Windows Build Instructions

### ISSUE THREAD

**Issue by Dullstar** [SimonN/LixD#421]
The current instructions state:

`Extract this into your LDC directory. You will get new DLLs in bin/ and
new LIBs in lib/. Proceed to the next section, "Get the Lix source".`

I do not know if this may have been accurate at one time, but with ldc2-1.26.0, there are folders called "lib32" and "lib64". If I follow the instructions as written and place the libs in a folder called lib, this will not work; Lix will compile, but a linker error will occur.

Placing the lib files in lib64 works.

**Comment by Dullstar** [comment]
The instructions would benefit from being updated to match the correct name anyway (assuming, of course, that the problem isn't just my linker being literally haunted), but ideally the download itself would be updated so extracting the zip would still work.

**Comment by SimonN** [comment]
Thanks, good catch. I'll fix the docs.

Right, since I recommend LDC, I should follow the LDC directory structure in my DLL archive. I'm planning to release 0.9.37 this weekend, and I'll update the DLL archive before the release.

**Comment by SimonN** [comment]
The Windows 64-bit build notes point to LDC's multilib release instead of to the pure 64-bit release. It's possible to use LDC's installer or LDC's 7z download.

One difference between multilib and pure 64-bit is that LDC's `lib/` dir is now called `lib64/` in multilib. I've updated my all-in-one DLL download (link is in my Windows build instructions) with the new directory name `lib64/` instead of `lib/`.

**Comment by SimonN** [comment]
It's a week after the release and I haven't heard any problems about the 0.9.37 build instructions. I'm closing this. If you find something, let me know!
