### ISSUE TITLE
Misorganized/Duplicated Levels

### ISSUE THREAD

**Issue by Dullstar** [SimonN/LixD#423]
I was testing a utility to check for duplicate files I was making to help someone organize a collection of files they had, and the folder I was testing with happened to also contain the Lix source in one of the subdirectories. Looking through the results, I noticed several duplicated levels, all multiplayer levels; seems there's a mix of multiple files with different names, and some where there's a variant for a different number of players, but the level file is identical for both (including one that has a 6P title, but says it is intended for 8 players).

This file contains the output of that program when run on the Lix level folder.
It should be up to date with the current default branch of the repository as of 2021-06-06

(note that I didn't edit the output to change it to the relative paths)
[LixDupes.txt](https://github.com/SimonN/LixD/files/6603721/LixDupes.txt)

**Comment by SimonN** [comment]
Thanks, great housekeeping! I've pushed the changes to the stable master branch. If you like, double-check the tree. I changed:

* `8p/` had duplicates of all other _Along the Fabrics of Your Clothing_, I removed the dupes from `8p/` and kept the files in the correct player directories.
* I removed `perfectsituation-2p.txt` (with dash) and kept `perfectsituation2p.txt` (no dash) because that's the more common pattern.

The `_order.X.txt` happens to be the same, I've tried to sort more interesting authors to the top, but it's a symptom of the less-than-optimal level directory structure. Level selection should be more like browsing a database, not like browsing a directory tree.
